# Generated by Django 6.0.4 on 2026-04-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('color', models.CharField(choices=[('blanco', 'Blanco'), ('negro', 'Negro'), ('azul', 'Azul'), ('borgona', 'Borgoña'), ('marron', 'Marrón')], default='negro', max_length=20)),
                ('talla', models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='3', max_length=2)),
                ('destacado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
