# Generated by Django 6.0.3 on 2026-05-13 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tienda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_envio', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('razon_social', models.CharField(default='Cliente FFAME HEELS', max_length=150)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('banco', models.CharField(default='BBVA México', max_length=80)),
                ('numero_cuenta', models.CharField(default='**** **** **** 1234', max_length=30)),
                ('titular_cuenta', models.CharField(default='FFAME HEELS SA DE CV', max_length=150)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='web_tienda.orden')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=140)),
                ('telefono', models.CharField(max_length=20)),
                ('calle', models.CharField(max_length=160)),
                ('colonia', models.CharField(max_length=120)),
                ('ciudad', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=120)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('pais', models.CharField(default='México', max_length=60)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_envio', to='web_tienda.orden')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=160)),
                ('producto_talla', models.CharField(blank=True, max_length=20)),
                ('producto_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web_tienda.orden')),
            ],
        ),
        migrations.CreateModel(
            name='PagoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=20)),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=20)),
                ('titular', models.CharField(max_length=140)),
                ('ultimos_4', models.CharField(max_length=4)),
                ('referencia', models.CharField(max_length=40, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='web_tienda.orden')),
            ],
        ),
    ]
